version: '2'

services:
  broker:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: broker
    expose: 
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookmaker_broker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwe123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=bookmaker_broker